In [22]:
import numpy as np

In [23]:
def next_invJ(invJ, F, next_F, x, next_x):
    delx = next_x - x
    delF = next_F - F
    denom = (delx.dot(invJ)).dot(delF)
    numer = delx - invJ.dot(delF)
    frac = numer/denom
    adjustment = frac.dot(delx)*invJ
    return invJ - adjustment

In [24]:
def first_invJ(J):
    if (J.shape[0] != J.shape[1]): #if over determined
        return (np.linalg.inv((np.transpose(J)).dot(J))).dot(np.transpose(J))
    else:
        return np.linalg.inv(J)

In [25]:
def F_solve(x):
    f0 = (3*x[0]) - (x[1]*x[2])-(1.5)
    f1 = 4*x[0]*x[0] - 625*x[1]*x[1] + 2*x[2] - 1
    f2 = 20*x[2] + x[1]*x[1] + 9*x[0]
    f3 = 56.2*x[1]*x[2] - x[0]
    return np.array([f0, f1, f2, f3])
    

In [26]:
x = np.array([1,1,1])
J = np.array([[3, x[2], -1*x[1]], 
            [8*x[0], -1250*x[1], 2], 
            [9, 2*x[1], 20],
             [-1, 56.2*x[2], 56.2*x[1]]])

In [27]:
def BroydensMethod(max_iteration, x, J):
    invJ = first_invJ(J)
    
    for i in range(max_iteration):
        print('This is the ' + str(i) + ' iteration.')
        print('This X: ' + str(x))
        F = F_solve(x)
        next_x = x - invJ.dot(F)
        next_F = F_solve(next_x)
        
        # Updating everything
        invJ = next_invJ(invJ, F, next_F, x, next_x)
        x = next_x
        print('next_invJ:')
        for i in range(3):
            print(str(invJ[i]))
        print('next_x: ' +str(x)+ '\n')
        
    return x
        

In [28]:
BroydensMethod(15,x,J)

This is the 0 iteration.
This X: [1 1 1]
next_invJ:
[ 0.03857573 -0.00143499  0.10409742 -0.03630788]
[ 0.00024876 -0.00086977  0.00066774 -0.00020225]
[-0.00183196  0.00083004  0.00192017  0.01842592]
next_x: [-0.88198129  0.49115064  0.48100906]

This is the 1 iteration.
This X: [-0.88198129  0.49115064  0.48100906]
next_invJ:
[-0.00944318  0.00035128 -0.02548263  0.00888802]
[-6.08947932e-05  2.12916529e-04 -1.63459751e-04  4.95100921e-05]
[ 0.00044846 -0.00020319 -0.00047005 -0.00451059]
next_x: [-0.61102678  0.36535953  0.33098456]

This is the 2 iteration.
This X: [-0.61102678  0.36535953  0.33098456]
next_invJ:
[-0.11099003  0.00412874 -0.29950896  0.10446498]
[-0.00071572  0.00250251 -0.00192122  0.00058191]
[ 0.00527092 -0.00238818 -0.00552471 -0.05301503]
next_x: [-0.64862412  0.38250501  0.34981651]

This is the 3 iteration.
This X: [-0.64862412  0.38250501  0.34981651]
next_invJ:
[-0.29101407  0.01082549 -0.78530766  0.27390548]
[-0.00187662  0.00656153 -0.0050374   0.00152

<ipython-input-25-bd187d82b6ee>:2: RuntimeWarning: overflow encountered in double_scalars
  f0 = (3*x[0]) - (x[1]*x[2])-(1.5)
<ipython-input-25-bd187d82b6ee>:3: RuntimeWarning: overflow encountered in double_scalars
  f1 = 4*x[0]*x[0] - 625*x[1]*x[1] + 2*x[2] - 1
<ipython-input-25-bd187d82b6ee>:3: RuntimeWarning: invalid value encountered in double_scalars
  f1 = 4*x[0]*x[0] - 625*x[1]*x[1] + 2*x[2] - 1
<ipython-input-25-bd187d82b6ee>:4: RuntimeWarning: overflow encountered in double_scalars
  f2 = 20*x[2] + x[1]*x[1] + 9*x[0]
<ipython-input-25-bd187d82b6ee>:5: RuntimeWarning: overflow encountered in double_scalars
  f3 = 56.2*x[1]*x[2] - x[0]


array([nan, nan, nan])